---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
    - shnee.os_release
  tasks:
  - name: Example assertion
    debug:
      var: os_release
  - name: Verify that os-release match our expected values.
    assert:
      that:
        - os_release.ID == 'centos'
        - os_release.ID_LIKE == 'rhel fedora'
